name: CD

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy_dev:
    name: Deploy Dev
    uses: ./.github/workflows/step-deploy.yml
    with:
      env: dev
      resource_group_name: rg-devops-days-dev
      app_service_name: app-devops-days-dev
    secrets: inherit

  deploy_prod:
    name: Deploy Prod
    needs: deploy_dev
    uses: ./.github/workflows/step-deploy.yml
    with:
      env: prod
      resource_group_name: rg-devops-days-prod
      app_service_name: app-devops-days-prod
    secrets: inherit
