name: CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_dev:
    name: Deploy Dev
    uses: ./.github/workflows/step-deploy.yml
    with:
      env: dev
      resource_group_name: rg-icc-dev
      app_service_name: app-icc-dev
    secrets: inherit

  deploy_test:
    name: Deploy Test
    needs: deploy_dev
    uses: ./.github/workflows/step-deploy.yml
    with:
      env: test
      resource_group_name: rg-icc-test
      app_service_name: app-icc-test
    secrets: inherit

  deploy_prod:
    name: Deploy Prod
    needs: deploy_test
    uses: ./.github/workflows/step-deploy.yml
    with:
      env: prod
      resource_group_name: rg-icc-prod
      app_service_name: app-icc-prod
    secrets: inherit
